### ISSUE TITLE
ModuleNotFoundError: No module named 'llava'

### ISSUE THREAD

**Issue by matsumura-y1** [JiwanChung/vlis#1]
### Description:
I encountered an error while trying to run the script `ui.py` in the llava project. The error traceback is as follows:

```
Traceback (most recent call last):
  File "/home/matsumura/mysource/vlis/code/llava/ui.py", line 18, in <module>
    from generate import GenerationModel
  File "/home/matsumura/mysource/vlis/code/llava/generate.py", line 7, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'
```

### Steps to Reproduce:

1.  Clone the repository.
2.  Navigate to the llava directory.
3.  Run the `ui.py` script using Python.

Can you please provide guidance on how to resolve this issue?

Thank you.

**Comment by JiwanChung** [comment]
Hi! Thank you for your attention to our work.

It seems there is a bug on our end. We will update the code to resolve this issue and ensure compatibility with more recent versions of LLava. In the meantime, please try the following fix.

```
cd LLaVA
cp -r llava ../
```

**Comment by matsumura-y1** [comment]
Thank you for your prompt response! After making the suggested changes, I encountered a new error. Could you please provide a solution? Thank you for your assistance.

Traceback (most recent call last):
```
File "/home/matsumura/mysource/vlis/code/llava/ui.py", line 18, in <module>
    from generate import GenerationModel
File "/home/matsumura/mysource/vlis/code/llava/generate.py", line 7, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
File "/home/matsumura/mysource/vlis/code/llava/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
File "/home/matsumura/mysource/vlis/code/llava/llava/model/__init__.py", line 1, in <module>
    from .llava import LlavaLlamaForCausalLM, LlavaConfig
File "/home/matsumura/mysource/vlis/code/llava/llava/model/llava.py", line 329, in <module>
    AutoConfig.register("llava", LlavaConfig)
File "/home/matsumura/myENV/Python3.11.7/myVLIS_llava/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1023, in register
    CONFIG_MAPPING.register(model_type, config, exist_ok=exist_ok)
File "/home/matsumura/myENV/Python3.11.7/myVLIS_llava/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 722, in register
    raise ValueError(f"'{key}' is already used by a Transformers config, pick another name.")
ValueError: 'llava' is already used by a Transformers config, pick another name.

```
